# Site settings
title: hxx.io
email: yellowstar520@gmail.com
description: hxx's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.hxx.io" # the base hostname & protocol for your site
twitter_username: yellowstar520
github_username:  hxx
disqus_shortname: hxxio
google_analytics_id: UA-45822478-2

# Build settings
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:     [autolink, tables]
